# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - features

language: node_js
node_js:
  - "node"

script: 
  - typings install
  - npm test