# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - features

dist: trusty
language: node_js
node_js:
  - "5"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - npm run test:travis
  - npm run test:mocha:travis